### ISSUE TITLE
viscone out bounds cap test

### ISSUE THREAD

**Issue by meshstyles** [frasolution/DN_MM_Hunter#3]
no I doubt a outOfBoundsException catch will continue in siuations wher the upper part just is out of bounds

**Comment by meshstyles** [comment]
This might be a issue with fill test since the overlap test iterates only through the valid array positions

**Comment by meshstyles** [comment]
The problem seem to be in fillAct(var var var var) and we seem to revamp the out bounds cap
Just do a cap for each coordinate like
`if(outBounds Cond){} `

also the console issue for the x= 8  and y = 3 start coords
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10
        at viscone.fillAct(viscone.java:41)
        at viscone.fillStart(viscone.java:29)
        at viscone.main(viscone.java:10)

**Comment by meshstyles** [comment]
Fixed the problem with start point 0 2 is that you would think it misses a star but rather it shows the colission point here.
The problem that the rest will not be drawn still consits and problay will be fixed by deleting the current out bound condition and returning as working array once the length has been reached. This was missed here regardless.

**Comment by meshstyles** [comment]
The fix did not worked as planed we get this pattern
`
+++****+++
++****++++
+*****++++
++***+++++
+++**+++++
++++++++++
++++++++++
++++++++++
++++++++++
++++++++++ `

**Comment by meshstyles** [comment]
This has been Tested for o.getOri() == 0
now optimize the code that for other Orientations it will only test once and than the Module is finished
THREAD WILL BE LOCKED AFTER THIS POINT PLEASE OPEN NEW THREAD FOR LATER ISSUES
