### ISSUE TITLE
genOriTest.java values 8 9 6

### ISSUE THREAD

**Issue by meshstyles** [frasolution/DN_MM_Hunter#7]
lease enter x y objectCount
8 9 6
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 8
        at genOriTest.overArr(genOriTest.java:146)
        at genOriTest.verifVec(genOriTest.java:71)
        at genOriTest.oriVecCreaVector(genOriTest.java:56)
        at genOriTest.main(genOriTest.java:18)

**Comment by meshstyles** [comment]
after analysis problem seems to be related to y being larger than x

**Comment by meshstyles** [comment]
seems like the plane[axis] - 1 was more like plane[axis] - 0 so this should be fixed

**Comment by meshstyles** [comment]
there is now a visible discrapanc for the independence of the array sizes. This needs to be addressed at a later point.
Another major point is that vecPlane gets bigger after safety override
